apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ds-project-api-canary
  namespace: ds-project
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: ds-project.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ds-project-api-canary
                port:
                  number: 80
