apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ds-project-api
  namespace: ds-project
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ds-project.example.com
      secretName: ds-project-api-tls
  rules:
    - host: ds-project.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ds-project-api
                port:
                  number: 80