global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ds-project-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: ds-project-api
          environment: development

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
